server:
  port: 9000
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:   # gateway配置路由信息开始
        # spring.cloud.gateway.routes[0].predicates[0]
        - id: gateway-shanghai
          uri: lb://shanghai
          predicates:
            - Path=/sh/**
            - Between=2022-05-07T15:32:03.138+08:00[Asia/Shanghai],2022-05-07T15:42:03.138+08:00[Asia/Shanghai]
        - id: gateway-beijing # 设置路由的id,和其他任何名称没有关联,只是不能和其他路由id重名即可
          # uri表示设置路由的目标
          # lb是LoadBalance(负载均衡)的缩写 beijing是注册到nacos的服务名称
          uri: lb://beijing
          # predicates是断言 所谓断言就是判断一个条件,如果满足的话就做某些指定的操作
          predicates:
            # Path表示判断是否满足路径条件,如果访问当前网关项目的路径是/bj/**,
            # name本次访问网关的路由目标就是uri指定的路径
            - Path=/bj/**
            # http://localhost:9000/bj/show



