server:
  port: 9000
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        # 网关也是微服务项目的一部分,所以也要注册到Nacos
        server-addr: localhost:8848
    gateway:
#      discovery:
#        locator:
#          # 开启网关动态路由的配置
#          # 默认的路由规则:在网关端口号后,先编写要路由到的目标服务器
#          #              注册到Nacos的名称,再编写要访问的具体路径
#          # 例如 localhost:9001/bj/show  ->  localhost:9000/beijing/bj/show
#          enabled: true
      # routes就是路由的意思,下面的内容就是配置路由,它是一个数组类型的属性
      routes:
        - id: gateway-shanghai
          uri: lb://shanghai
          filters:
            - AddRequestParameter=age,18
          predicates:
            - Path=/sh/**
            # After是时间断言,判断访问时间是否指定时间之后
            # 如果早于这个时间,访问结果时404,晚于这个时间才能正常访问, 和上面Path断言是"与"的关系
            # - After=2022-11-25T11:53:50.087+08:00[Asia/Shanghai]
            # - Before=2022-11-25T14:17:30.087+08:00[Asia/Shanghai]
            # - Between=2022-11-25T14:20:15.087+08:00[Asia/Shanghai],2022-11-25T14:20:30.087+08:00[Asia/Shanghai]
            # Query断言判断请求中是否包含指定的参数名称(username)的参数,如果不包含就发生404错误
            - Query=username



          # 数组类型属性赋值时,每个数组元素都要以"-"开头,一个"-"之后的所有内容,都是这个元素包含的值
          # id表示当前路由的名称,和之前出现过的任何名字没有关联,唯一的要求就是不能和之后出现的路由id重复
        - id: gateway-beijing
          # uri配置路由的目标服务器,beijing是服务器注册到nacos的名称
          # lb就是LoadBalance的缩写
          uri: lb://beijing
          # predicates是断言的意思,指满足某些条件的之后执行某些操作
          predicates:
            # predicates属性也是数组类型,赋值要以"-"开头
            # 这个断言的含义就是如果访问网关项目的路径以/bj/开头,路由访问beijing服务器
            # ↓ P要大写     **是通配任何路径
            - Path=/bj/**








