server:
  port: 9000
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        # 网关也是微服务项目的一个模块,需要注册到Nacos才能生效
        server-addr: localhost:8848
    gateway:
      # routes是路由的意思,表示开始配置路由设置,它是一个数组的类型
      routes:
          # 数组类型赋值时,每个数组元素都要以"-"开头,一个"-"之后的所有内容,都是这个元素包含的内容
          # id表示当前路由的名称,这个名称和之前我们学习的任何名称没有关联,
          # 唯一的要求就是不能和之后出现的路由id重复
        - id: gateway-beijing
          # uri是设置当前路由配置的目标服务器名称,"beijing"就是目标服务器注册到nacos的名称
          # lb就是LoadBalance的缩写,意思是当前路由支持负载均衡
          uri: lb://beijing
          # predicates是断言的意思,断言指满足某些条件时执行某些操作的设置
          predicates:
            # predicates属性也是数组类型的设计,赋值也要以"-"开头
            # 这个断言的含义就是如果访问当前网关项目路径以/bj/开头,那么就路由访问beijing服务器
            # ↓ P要大写!!!!!   **是通配任何路径
            - Path=/bj/**










