server:
  port: 9000
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        # 网关也是微服务项目的一个模块,需要注册到Nacos才能生效
        server-addr: localhost:8848
    gateway:
#      discovery:
#        locator:
#          # 开始SpringGateway动态路由功能的配置
#          # 动态路由的默认路由规则: 在网关路径端口号后,先编写要路由的目标服务器名称
#          #                     也就是注册到Nacos的名称,再编写要求访问的具体路径
#          # 例如要访问 localhost:9001/bj/show -> localhost:9000/beijing/bj/show
#          enabled: true
      # routes是路由的意思,表示开始配置路由设置,它是一个数组的类型
      routes:
        - id: gateway-shanghai
          uri: lb://shanghai
          filters:
            - AddRequestParameter=age,18
          predicates:
            - Path=/sh/**
            # Query断言判断请求中是否包含指定的参数名称(username),如果不包含就无法访问,发送404错误
            - Query=username
            # - Between=2022-12-29T09:51:35.345+08:00[Asia/Shanghai],2022-12-29T09:51:50.345+08:00[Asia/Shanghai]
            # - Before=2022-12-29T09:45:55.345+08:00[Asia/Shanghai]
            # After是内置的时间断言,判断访问发生的时间是不是指定时间之后
            # 如果早于这个时间,会报404错误,必须晚于这个时间才能正常访问
            # 和上面Path配置的断言是"与"的关系
            # - After=2022-12-28T17:38:10.345+08:00[Asia/Shanghai]
          # 数组类型赋值时,每个数组元素都要以"-"开头,一个"-"之后的所有内容,都是这个元素包含的内容
          # id表示当前路由的名称,这个名称和之前我们学习的任何名称没有关联,
          # 唯一的要求就是不能和之后出现的路由id重复
        - id: gateway-beijing
          # uri是设置当前路由配置的目标服务器名称,"beijing"就是目标服务器注册到nacos的名称
          # lb就是LoadBalance的缩写,意思是当前路由支持负载均衡
          uri: lb://beijing
          # predicates是断言的意思,断言指满足某些条件时执行某些操作的设置
          predicates:
            # predicates属性也是数组类型的设计,赋值也要以"-"开头
            # 这个断言的含义就是如果访问当前网关项目路径以/bj/开头,那么就路由访问beijing服务器
            # ↓ P要大写!!!!!   **是通配任何路径
            - Path=/bj/**










